---
- hosts: all
  remote_user: root

  # create a variable named "proxy_env" that is a dictionary
  vars:
    proxy_env:
      http_proxy: http://10.254.0.254:8080
      https_proxy: http://10.254.0.254:8080 
      ftp_proxy: http://10.254.0.254:8080

        - name: Install a .deb package from the internet
  ansible.builtin.apt:
    deb: https://google-chrome-stable_current_amd64.deb
